# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-16 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_time']},
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(db_index=True, default=1, upload_to='products/%Y/%m/%d', verbose_name='村落背景大图（为了更好地展现，建议宽度1920px，高度600px）'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(db_index=True, max_length=200, verbose_name='村落基本信息'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.CharField(db_index=True, max_length=20, verbose_name='村落摘要'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=8, verbose_name='村落名称'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
