# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-12 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ourstory', '0005_auto_20180806_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='storycontent',
        ),
    ]
